run:
  concurrency: 4

  timeout: 5m

  issues-exit-code: 2

  modules-download-mode: mod

  allow-parallel-runners: false

  go: '1.17.8'


output:
  format: colored-line-number
  print-issued-lines: true
  uniq-by-line: true
  gci:

    sections:
      - standard                       # Captures all standard packages if they do not match another section.
      - default                        # Contains all imports that could not be matched to another section type.
      - prefix(github.com/HalvaPovidlo/halvabot-go) # Groups all imports with the specified Prefix.

    section-separators:
      - newLine

linters:
  disable-all: true
  enable:
    # - deadcode
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # - misspell
    - nolintlint
    - goimports
    - nakedret
    - unconvert
    - whitespace
    - gosimple
    - govet
    - ineffassign
    - gocritic
    - revive
linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true