name: mock_deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S_NAME: ${{ secrets.YANDEX_SERVER_NAME }}
      S_PASSWORD: ${{ secrets.YANDEX_SSH }}
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.YANDEX_SSH }}
          known_hosts: ${{ secrets.YANDEX_HOST }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.8

      - name: Build mock
        run: go build -o deployments/botmock cmd/botmock/main.go

      - name: Deploy
        run: |
          rsync -avze "ssh -o StrictHostKeyChecking=no" deployments/* "$S_NAME":/home/halva/gobot/
          ssh -o StrictHostKeyChecking=no "$S_NAME" /home/halva/gobot/restartBot.sh -m
