name: tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.19]
    name: Tests Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Run tests
        run: go test ./...
